# Generated by Django 2.2.3 on 2019-07-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=20, unique=True)),
                ('nickname', models.CharField(default='匿名', max_length=20)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_md5', models.CharField(max_length=128)),
                ('image_path', models.CharField(max_length=100)),
                ('image_date', models.CharField(max_length=50)),
                ('image_kind', models.CharField(max_length=20)),
                ('image_type', models.CharField(max_length=20)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserInfo', to_field='openid')),
            ],
        ),
    ]
